### ISSUE TITLE
Problem with user macros in Zabbix 5.4

### ISSUE THREAD

**Issue by aglumov** [mverboom/zabbix-pve-api#10]
Hello!
I've found that zabbix 5.4 has some problems with macros: {$PVESECRET} and {$PVETOKENID}
When header value is set following way: PVEAPIToken=root@pam!zabbix=abcdefg1-878a-abcd-1234-9ef8b3bf9738
item gets value.
But when I set header value this way: PVEAPIToken={$PVETOKENID}={$PVESECRET}
Item became unsupported and I get error 'Response code "401" did not match any of the required status codes "200"'
The macros are set in host macros list. Also tried set macros in template, not working too.

I use:
zabbix_server (Zabbix) 5.4.9
pve-manager/7.1-8/5b267f33 (running kernel: 5.13.19-2-pve)

I suppose that zabbix sends macros name instead of value, but I cann't find any api or http requests logs.

**Comment by mverboom** [comment]
Hi,

I've looked at my zabbix server (5.4 with proxmox 7.1) and can't see any problems with authentication.
My configuration is set like this:
Go to configuration of host that is connecting to the API
Go to macro's
Create Host Macro's for:
{$PVETOKENID} and {$PVESECRET}

That works for my installation.

Regards,

Mark

**Comment by aglumov** [comment]
It suddenly began to work. But I used host's macros, not template's.
I'll try to check out with template and give a feedback.

**Comment by mverboom** [comment]
Hi,

Sorry, I do not understand. Did you define the macro's within the template? If so, you should not do that. The macro's should be defined on the host level. Authentication information for the API is specific for the host. The template is generic for all systems that you are monitoring with it. So defining API information in macro's there is not the right place.

This is the way I tried to describe it in the documentation..

Regards,

Mark
