### ISSUE TITLE
Template import to Zabbix 6.0 error

### ISSUE THREAD

**Issue by begize** [mverboom/zabbix-pve-api#11]
Hi:
    i import  failed this template to zabbix 6.0, it's import failed details is: 
Cannot find graph "CPU ({{HOST.HOST}:pveapi.node.cpus.last(0)} CPU(s))" used in dashboard "Overview".

Please help to fix it ,thanks~~

Regards,

**Comment by mverboom** [comment]
Hi,
I have not had the time to upgrade to zabbix 6. As the readme states, the template is for 5.4 at the moment.
As soon as I have time I am going to look into this. In the mean time, if you have any fixes, please share.

Regards,

Mark

**Comment by nobrainer-de** [comment]
Hey there, you got any news for us? Was testing this now, got only the Node name, and status of the cluster (1 for online). No further data points.

**Comment by mverboom** [comment]
Hi,
So I guess the import works on 6 as you get information? This issue was regarding the template import on zabbix 6, so that has been resolved.
Based on that you mention I can't say what is wrong. Can you open a specific issue and provide at least some information?
Regards,
Mark
