### ISSUE TITLE
No Values received through API Access - zabbix 6.0 / pve 7.2.3

### ISSUE THREAD

**Issue by nobrainer-de** [mverboom/zabbix-pve-api#12]
Hi there,

I just imported the template succesfully in zabbix 6.0 and also i established a API Connection to my PVE Cluster (at this moment only 1x Node).

The problem is, that zabbix could only get the node information but no data thereself.
![2022_05_17_17_18_50_Zabbix_Host_Latest_data](https://user-images.githubusercontent.com/60841834/168847395-a1fc8655-3afa-45b9-97e5-f5a1946be02c.png)

![2022_05_17_17_20_03_Zabbix_Host_Latest_data](https://user-images.githubusercontent.com/60841834/168847554-f666ff04-102d-45c0-8b89-4caeab2e6e6a.png)

As you can see, the Node was sucesful added as a new host. But no further Data will be collected.

Here are my API Rights for the specific node:

![grafik](https://user-images.githubusercontent.com/60841834/168847717-91def97c-a547-4e71-9231-8fb17fa2accc.png)

![grafik](https://user-images.githubusercontent.com/60841834/168848200-8dd0f591-03ae-4abf-8091-56e205bb8519.png)

I also set some specific VMs for testing but no changes happend.

After this i wanted to discover manually on the node, I get this from zabbix:

![grafik](https://user-images.githubusercontent.com/60841834/168848507-faccc541-dc33-428d-835f-1816c18ca8b7.png)

Any ideas for debugging or wrong configuration maybe?

**Comment by mverboom** [comment]
Hi,
The first thing I would check is the set of permissions that are associated with the API token. Have seen this behaviour when the API token hasn't got enough permissions.

**Comment by mverboom** [comment]
Sorry, missed your screenshots (was on ascii mail). Is there any information in /var/log/pveproxy/access.log?

**Comment by nobrainer-de** [comment]
[PVE_Logfile_PVEProxy.txt](https://github.com/mverboom/zabbix-pve-api/files/8717176/PVE_Logfile_PVEProxy.txt)

There You go. i censored the monitoring IP.

Looks like there are a lot of Acces Problems (403) hm... maybe i should check the API Rights again

**Comment by mverboom** [comment]
It looks like it might be a permission problem. Just to rule it out you could give all permissions to see if the problem then goes away, just to test if it is only permission related.

**Comment by nobrainer-de** [comment]
hm i changed the right of token api to administrator, nothing changed at all

**Comment by mverboom** [comment]
Is privilege separation enabled for the api token?

**Comment by nobrainer-de** [comment]
yes it is

tried it now with disabled seperation, nothing changed

**Comment by mverboom** [comment]
Very strange.. I can't reproduce this from here, the api calls work fine (also outside of zabbix). Have you tested API access outside of zabbix to see if that works?

**Comment by nobrainer-de** [comment]
maybe i did a mistake, but i deleted all rights and readded them to my monitoring USER and API Token it works now and is shown in the rights sight of api token.

Thanks for your time!
