### ISSUE TITLE
Is test pool matching implemented yet?

### ISSUE THREAD

**Issue by SupersonicWaffle** [mverboom/zabbix-pve-api#13]
Hi,

been loving this template so far but I hit a snag trying to configure {$PVETESTPOOL}.
Looking at the ToDos it seems like this functionality is not implemented yet?

Best Regards

**Comment by SupersonicWaffle** [comment]
After some digging I found this error message in the pool check item

`cannot extract value from json by path "$.body.data[?(@.poolid=="{#PVEQEMUPOOL}")].poolid.first()": cannot close top level object`

**Comment by mverboom** [comment]
Hi,
I started on the testpool functionality, but wanted to remove it. I don't want to rely on the pool to exclude systems, but I think it
would be better to make some name matches, just like with snapshots. However, that is not implemented yet..
I took a quick look at triggers for lxc containers, and all triggers still seem to check for membership of the testpool name. So as long as you've set the macro to the name of the test pool and put the lxc containers in the pool in proxmox, it should work I guess.

Regards,

Mark

**Comment by SupersonicWaffle** [comment]
Hi Mark,

thanks for your response. Unfortunately I don't have any lxc containers to test. QEMU VMs all return 1 in the "Pool check" item for me, this means that all my VM templates triggers fire because they're not running.
I will disable the triggers for now. A feature akin to how you can exclude snapshots would be great. I'm just starting out with zabbix, once I'm more familiar I'll look into whether I can contribute.

Best Regards

**Comment by mverboom** [comment]
Hi,

I've checked the triggers vor the qemu vm's, and they also have the poolcheck in there.

What should be happening is that through the API the poolname is found for the specific qemu system.
That pool name is matched to the macro PVETESTPOOL. The value of this marco is per default defined in the pve api settings template and set to "test".

I've not verified this, but if this old behaviour works, then when a qemu system is put into the pool test inside the proxmox system, the triggers should not go off.

Is this the exact situation you created?

Regards,

Mark

**Comment by SupersonicWaffle** [comment]
Hi Mark,

yes I have created a test pool but triggers still fire on members that are shut off.

Best Regards

**Comment by duiffie** [comment]
The macro should be set on the host object which has the datacenter template assigned. PR #15 should improve the functionality of PVENOPROBLEMPOOL (former PVETESTPOOL) by being able to use true regex in the macro.

**Comment by mverboom** [comment]
Merged request.
