### ISSUE TITLE
no data receiving

### ISSUE THREAD

**Issue by einor9** [mverboom/zabbix-pve-api#17]
Hi,
Zabbix 6.0 and Proxmox VE 8.1.4. I imported zabbix-pve-api-v0.1.json as template, set macros and set permissions for api token.

I see only following data after all: Cluster nodes, Cluster nodes online, Node mynode online, pveapi datacenter master resources (long json data) and pveapi datacenter master tasks (long json data). Did I miss something to install ?

**Comment by mverboom** [comment]
Not sure based on your information. Maybe permission issue? You might try adjusting permissions for the api token:

Try Datastore, Mapping, Pool, SDN, Sys and VM audit permissions

**Comment by einor9** [comment]
Yes, it was permission issue. You cannot just set permission to API Token, you must set same permission to corresponding user. You can close this case.
