### ISSUE TITLE
LXC Containers that are not locked trigger errors

### ISSUE THREAD

**Issue by wehde92** [mverboom/zabbix-pve-api#2]
In the /var/log/zabbix/zabbix_server.log you get a bunch of these complaints:

` Failed: cannot extract value from json by path "$.body.data.lock": no data matches the specified path`

When manually dumping the data from the API you will see there is not lock value in the json for a specific container.

**Comment by mverboom** [comment]
Hi,

I think I found the source of this issue. I am going to export my fix, but as I'm running zabbix 5.4, it might be a problem importing this into an older version. I will outline the fix I've done:
* Go to Configuration -> Templates
*  Click Template pve api lxc
* Click on items
* Click on pveapi lxc master status: lock
* Click on Preprocessing
* Check the box Custom on fail
* Set it to: Set value to and leave the value empty
* Press update
That seems to have solved it on my side.

Regards,

Mark

**Comment by wehde92** [comment]
That seems to have fixed it. Thanks much!

**Comment by YARYKGOOD** [comment]
Hello. I have Zabbix 5.0.14 . I can't configure zabbix-pve-api. Please tell me what's wrong, tokenId how to do and how to configure? I 'm a beginner , I want to monitor virtual machines

**Comment by mverboom** [comment]
Not sure what this has to do with this closed issue, but the template should work on zabbix 6 (see documentation).

Regards,

Mark

**Comment by YARYKGOOD** [comment]
I understand that the template works on 6.0, but it doesn't work on 5.0. Tell me, what am I doing wrong?

**Comment by mverboom** [comment]
As far as I am aware, you can't load a template exported on a specific version on an older version. So you can't import a template exported for zabbix 6 on zabbix 5.

**Comment by YARYKGOOD** [comment]
I found an archive on zabbix 5.0 with you, but the template does not work,the template created these two nodes in the network nodes, but does not remove data from

**Comment by mverboom** [comment]
Yes, the template started out on an older version of zabbix and proxmox. I have neither of those versions available and am not developing for those versions.
The template seems to work ok for Promox 7 with Zabbix 6 though.

Regards,

Mark

**Comment by YARYKGOOD** [comment]
pve api master cluster writes {"body":{"data":[{"status":"online","type":"node","node":"xxx2","level":"","id":"node/xxx2"},{"type":"node","node":"xxx1","level":"","id":"node/xxx1","status":"online"}]}}

**Comment by YARYKGOOD** [comment]
Hello, Tell me, in the node of the virtual machine, I choose the template Template php api datacenter, and prescribe macros and that's it? Because in 6 zabbix and 7 proxmox writes the same way as in 5 zabbix

**Comment by YARYKGOOD** [comment]
The datacenter template finds a Node (Application: PVE Node) and that's it

pveapi node master lvm writes - Response code "403" did not match any of the required status code "200"

and so on . The template finds only the node , but does not remove other information
