### ISSUE TITLE
CPU item flapping

### ISSUE THREAD

**Issue by uldiseihenbergs** [mverboom/zabbix-pve-api#5]
I have full zabbix log of these:
```
  1379:20210626:170005.684 item "proxmoxServer:CPU500" became not supported: Preprocessing failed for:.
1. Failed: cannot apply multiplier "100" to value of type "string": cannot convert value to numeric type
  1377:20210626:170035.717 item "proxmoxServer:CPU500" became supported
```
i looked at full json returned by api - it looks strange to me that CPU value is in different place of each polling..
i don't know if this is an issue. 
full data below:
```
{"body":{"data":{"pid":"6153","cpus":8,"uptime":445487,"mem":7957336064,"blockstat":{"ide2":{"invalid_unmap_operations":0,"account_invalid":true,"unmap_total_time_ns":0,"flush_operations":0,"rd_bytes":10177252,"failed_flush_operations":0,"rd_merged":0,"wr_bytes":0,"wr_merged":0,"unmap_merged":0,"failed_wr_operations":0,"invalid_rd_operations":0,"invalid_flush_operations":0,"wr_total_time_ns":0,"account_failed":true,"invalid_wr_operations":0,"rd_total_time_ns":30781951,"idle_time_ns":445272656252192,"rd_operations":588,"failed_rd_operations":0,"wr_operations":0,"timed_stats":[],"failed_unmap_operations":0,"wr_highest_offset":0,"unmap_operations":0,"flush_total_time_ns":0,"unmap_bytes":0},"scsi1":{"rd_operations":138499,"wr_operations":195880,"failed_rd_operations":0,"timed_stats":[],"invalid_rd_operations":0,"wr_total_time_ns":173267482272,"invalid_flush_operations":0,"account_failed":true,"rd_total_time_ns":23479861720,"invalid_wr_operations":0,"idle_time_ns":2875718223,"unmap_operations":0,"flush_total_time_ns":4391900454,"unmap_bytes":0,"wr_highest_offset":26869792768,"failed_unmap_operations":0,"account_invalid":true,"flush_operations":67088,"unmap_total_time_ns":0,"invalid_unmap_operations":0,"unmap_merged":0,"failed_wr_operations":0,"rd_bytes":9232189952,"failed_flush_operations":0,"rd_merged":0,"wr_bytes":19206030848,"wr_merged":0}},"balloon":8589934592,"nics":{"tap500i0":{"netin":"563450375619","netout":"16807527840"}},"agent":1,"netin":563450375619,"spice":1,"diskwrite":19206030848,"name":"pagrabs","running-machine":"pc-q35-5.2+pve0","ballooninfo":{"mem_swapped_in":0,"actual":8589934592,"last_update":1624716002,"free_mem":414978048,"mem_swapped_out":0,"major_page_faults":1146850,"minor_page_faults":374379273,"total_mem":8372314112,"max_mem":8589934592},"qmpstatus":"running","maxmem":8589934592,"netout":16807527840,"maxdisk":0,"running-qemu":"5.2.0","cpu":0.0105814423379586,"disk":0,"ha":{"managed":0},"proxmox-support":{"pbs-masterkey":true,"pbs-dirty-bitmap":true,"pbs-dirty-bitmap-migration":true,"pbs-library-version":"1.0.3 (8de935110ed4cab743f6c9437357057f9f9f08ea)","query-bitmap-info":true},"vmid":"500","status":"running","template":"","diskread":9242367204,"freemem":414978048}}}
```

**Comment by mverboom** [comment]
Hi,

I put the json data you included in the template and got the correct cpu value back. Is this the actual API output that gives you the error?

Based on the error you are getting, it sounds like the cpu field might be empty. I've not checked this (template is still beta) but could it be the errors occur when the kvm is powered off?

Regards,

Mark

**Comment by uldiseihenbergs** [comment]
i overlooked all of these json data from particular VM, and all of them have CPU tag, so i don't know, why zabbix is complaining about those.
i have two of these VMs - both unraid and for both of them this error occurs - both VMs are online 24/7. 
i have bunch of other Linux and Windows VMs on this host, and these are just fine..
so, how to proof?
Thanks,
Uldis

**Comment by mverboom** [comment]
Hi,
I think if you put the zabbix server into debuglevel 4 it also puts (among a LOT of other stuff) in the logfile. Maybe it is possible to capture the exact data on which the error occurs.
If I can think of another way, I'll let you know.

Regards,

Mark

**Comment by uldiseihenbergs** [comment]
Ok, i will try then..
a funny thing is that CPU values in zabbix are updating just fine every the time - it's just logging that complains..

**Comment by uldiseihenbergs** [comment]
what a mess, i looked more closely at this issue, and discovered, that it's an item from different template.
so, sorry for your wasted time.
now i have more cleaner zabbix log, and i see more error and timeout messages from your template too, but i will create then new issue, if needed.
Thanks,
Uldis

**Comment by mverboom** [comment]
Ah, ok! No problem, thanks for letting me know :)

I've seen other messages too, am looking into it in the little time I have available at the moment..

Regards,

Mark
