### ISSUE TITLE
{$PVESERVER} tasks failed

### ISSUE THREAD

**Issue by uldiseihenbergs** [mverboom/zabbix-pve-api#6]
Hi, 
Can you provide Recovery expression for this trigger?
i have a it time to time once at night on the same time - looks like Proxmox is doing something internally..
Thanks

**Comment by uldiseihenbergs** [comment]
for me it happens always at 01:10 at night - exact on this time Proxmox is starting vzdump cron jobs for VM backups.

**Comment by mverboom** [comment]
Hi,

Making a recovery is a problem. Currently the trigger is raised when the number of failed tasks increases. This is not something that can recover.
I'm not sure if I understand the problem correctly. Is this trigger a false positive? So are there no failed tasks on the proxmox server but does the trigger go off anyway?

Regards,

Mark

**Comment by uldiseihenbergs** [comment]
Hi, 
problem is with this trigger shown below. i think it is not false-positive. but it have no "OK Event generation", so i must manually close it every time.
this trigger should occur, but next time, when when data from Proxmox comes in, it should close by himself.

![image](https://user-images.githubusercontent.com/60253253/123815132-e6c69980-d8fe-11eb-99b8-1f6de2e18a4d.png)

**Comment by mverboom** [comment]
That would kind of defeat the purpose of the trigger as far as I am concerned. Tasks should normally not fail. If an trigger generates an OK event on the next set of data, the faulty task will still be there but you won't be alerted when you look at zabbix.
If this trigger isn't working for your environment, I would disable the trigger either on the host instance of the template or on the template itself.

Regards,

Mark

**Comment by uldiseihenbergs** [comment]
> If an trigger generates an OK event on the next set of data, the faulty task will still be there but you won't be alerted when you look at zabbix.

that's not true for me - every trigger generates email message, so in my case i see one message with failed trigger, and another one with trigger recovery. that way works all Windows/Linux templates included in Zabbix. this is a reason why i ask this :)
but thanks anyway.

**Comment by mverboom** [comment]
I understand the reasoning. I do prefer (as with other templates) that the zabbix dashboard shows the state of all alerts and external state tracking through email/signal/sms etc.
I would prefer some other way of not running the trigger for "known not an issue" failed tasks. So making some kind of expression which would filter out failed tasks that are not important. But I'm not sure if that would be possible to build.

Another way would be to make a recovery trigger after a specified amount of time which is configurable through a macro. That way the macro would be able to determine if you want to auto close triggers for failed tasks or leave them open.

Regards,

Mark

**Comment by uldiseihenbergs** [comment]
OK, thanks for your explanation. i resolved this myself by just check "Expression" on OK event generation.
