### ISSUE TITLE
Enable item disk template Template pve api node

### ISSUE THREAD

**Issue by gabriel0029** [mverboom/zabbix-pve-api#7]
Hello, I saw that the master disks item of the pveapi node has nothing attached, and in the discovery rules the disk item prototype is disabled.
![image](https://user-images.githubusercontent.com/87427032/128644018-3f86f588-6006-4903-a6d9-a36f5bcec44d.png)

I tried to create my own collection item for the disks, but simply no information.
![image](https://user-images.githubusercontent.com/87427032/128644120-d62fcbd7-7e9d-4845-923d-6006078ac91e.png)

testing the item pveapi node master disks (http agent), brings me the necessary information, but in the latest data no information history. could you help me find the error?
![image](https://user-images.githubusercontent.com/87427032/128644339-c07ba751-aa71-4478-bdb2-0292f5368da2.png)

**Comment by mverboom** [comment]
Hi,

I started that part of the template a long time ago, but didn't get to debugging it. That is why it is currently disabled. It is on the things to do for the whole template set..

If you have any update/information on what needs to be done to get that part of the node template complete, that would be very helpful!

Regards,

Mark

**Comment by gabriel0029** [comment]
I managed to solve it, I'm evolving in the discoveries of the items, as soon as I have something more concrete I'll let you know to be added. another point I'm making is the template for version 5.0 of zabbix.

**Comment by mverboom** [comment]
I took a quick look at my notes. The problem with the disks was the way the wearout was reported. I tested this on my server which has SSD's, no problems. However, on another system with spinning disks the wearout is reported as N/A, which gives problems with the data, as those aren't numbers.
I'll try to take a look if I can easily fix that.

I don't have a zabbix 5.0 server available anymore, and as the backport from 5.4 is tricky, I'm not going to do that. With 5.4 a new syntax for expressions was introduced. So I'm moving forward with that setup. When the new LTS of zabbix is released (seems to be on the map for Q4) I will try and setup a development 6.0 zabbix server to maintain a template version for the latest LTS of zabbix.

Regards,

Mark

**Comment by mverboom** [comment]
Hi,

Did some changes to the disk monitoring. On my system it now seems to work without warning for disks that have no wearout information. I enabled the discovery rule by default now.

Regards,

Mark

**Comment by gabriel0029** [comment]
I didn't face this problem because my disks are ssd and there is no error, but I'm grateful for the adjustment.

I made some additions that for my scenario are interesting, they are (size, vendor, raid model, serial and scsi id). I don't know if it's interesting for you either.

Thank you for your willingness to help.

Greetings

**Comment by mverboom** [comment]
Hi,
Those are attributes I didn't include because for me it makes no sense to monitor them. I've yet to see a situation where I want to be alerted because of a change in size, vendor, raid model, serial or scsci id for a disk. It all takes up storage and processing on the zabbix server.
So I try to get the information out of PVE which should be interesting for monitoring. Other info is just available on the proxmox web interface or the systems themselves..

Regards,

Mark

**Comment by gabriel0029** [comment]
Problem resolved, sorry for the delay in finalizing the issue.
Thanks again.
Regards.
