### ISSUE TITLE
where is api-permissions.md?

### ISSUE THREAD

**Issue by user9931** [mverboom/zabbix-pve-api#8]
Sorry for stupid question but where i can find this file?

>   To assign least privileges to the token read the API-PERMISSIONS.md

**Comment by mverboom** [comment]
Sorry, forgot to commit..

**Comment by user9931** [comment]
by the way.. I'm running proxmox 6.4.4 its its strange - its local (that opens by click on help button) page dont mention Pool.Audit privilege, but https://pve.proxmox.com/wiki/User_Management have it. Maybe its about.. proxmox 7? What may be used instead?

> Node / System related privileges
> Permissions.Modify: modify access permissions
> Sys.PowerMgmt: Node power management (start, stop, reset, shutdown, …)
> Sys.Console: console access to Node
> Sys.Syslog: view Syslog
> Sys.Audit: view node status/config, Corosync cluster config and HA config
> Sys.Modify: create/remove/modify node network parameters
> Group.Allocate: create/remove/modify groups
> Pool.Allocate: create/remove/modify a pool
> Realm.Allocate: create/remove/modify authentication realms
> Realm.AllocateUser: assign user to a realm
> User.Modify: create/remove/modify user access and details.

**Comment by mverboom** [comment]
You don't have the PVEAuditor role? That is the one I use..

**Comment by user9931** [comment]
yes, thank you, will be using it. (its have Datastore.Audit SDN.Audit Sys.Audit VM.Audit)
